animal = "  chanCHito feliz  "
print(animal.upper())
# para repetirlo 3 veces, y de paso poner en mayuscula la palabra o el string
print((animal[0:5].upper())*3)
print(animal.lower())
print(animal.strip().capitalize())
print(animal.title())
print(animal.strip())
print(animal.lstrip())
print(animal.rstrip())
print(animal.find("CH"))
print(animal.find("cH"))
print(animal.replace("nCH", "j"))
print("nCH" in animal)
print("nCH" not in animal)